name: Final-CI

on:
  push:

jobs:
  run-system-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show folders (debug)
        run: |
          echo "ROOT:"
          ls -la
          echo "Module3:"
          ls -la Module3

      - name: Give permission
        run: chmod +x Module3/system-info.sh

      - name: Run script
        run: bash Module3/system-info.sh

      - name: Print success
        run: echo "Week 3 CI Successful"

